/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.import_export_text.ui;

import csheets.CleanSheets;
import csheets.core.Workbook;
import csheets.ext.import_export_text.CustomImportation;
import csheets.ext.import_export_text.ImportExportController;
import csheets.io.Codec;
import csheets.io.CodecFactory;
import csheets.ui.ctrl.UIController;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Carlos Silva <1130664@isep.ipp.pt>
 */
public class ExportDialog extends javax.swing.JDialog {

    private ImportExportController ieController;
    private UIController uiController;
    private CleanSheets app;
    private int checkChkHeader = 0;
    /**
     *
     */
    public ExportDialog(java.awt.Frame parent, boolean modal, UIController uiController, CleanSheets app) {
        super(parent, "Export Text Wizard", modal);
        this.uiController = uiController;
        this.app = app;
        this.ieController = new ImportExportController(uiController);
        initComponents();
        chkIncludeHeader.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblSeparator = new javax.swing.JLabel();
        txtSeparator = new javax.swing.JTextField();
        chkHeader = new javax.swing.JCheckBox();
        chkIncludeHeader = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        txtFileName = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSeparator.setText("Choose the column's separator:");

        txtSeparator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeparatorActionPerformed(evt);
            }
        });

        chkHeader.setText("Header");
        chkHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHeaderActionPerformed(evt);
            }
        });

        chkIncludeHeader.setText("Include Header");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose the file's name:");

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        txtFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 197, Short.MAX_VALUE)
                        .addComponent(btnExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(chkHeader)
                                    .addComponent(chkIncludeHeader)
                                    .addComponent(txtSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkIncludeHeader)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnExport))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        int header = 0;
        int includeHeader = 0;
        if (!txtSeparator.getText().isEmpty()) {
            if (!txtFileName.getText().isEmpty()) {
                try {
                    if (chkHeader.isSelected()) {
                        header = 1;
                    }
                    if (chkIncludeHeader.isSelected()) {
                        includeHeader = 1;
                    }
                    ieController.exportFile(app, txtFileName.getText() + ".txt", txtSeparator.getText(), header, includeHeader);
                    JOptionPane.showMessageDialog(null, "Your file has been exported to a text file", "Exportation Complete", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ExportDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else {
                JOptionPane.showMessageDialog(null, "Choose a file to be exported", "Warning", JOptionPane.WARNING_MESSAGE);
               
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Choose the column's separator", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void txtSeparatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeparatorActionPerformed

    }//GEN-LAST:event_txtSeparatorActionPerformed

    private void chkHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHeaderActionPerformed
        if ((!chkIncludeHeader.isSelected() || chkIncludeHeader.isSelected())  && checkChkHeader == 0) {
            chkIncludeHeader.setEnabled(true);
            checkChkHeader = 1;
            return;
        } else {
            chkIncludeHeader.setSelected(false);
            chkIncludeHeader.setEnabled(false);
            checkChkHeader = 0;
        }
    }//GEN-LAST:event_chkHeaderActionPerformed

    private void txtFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileNameActionPerformed
        
    }//GEN-LAST:event_txtFileNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExport;
    private javax.swing.JCheckBox chkHeader;
    private javax.swing.JCheckBox chkIncludeHeader;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSeparator;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtSeparator;
    // End of variables declaration//GEN-END:variables
}
