@startuml doc-files/insert_image_extension_design3.png
    participant "uic: UIController" as uic
    participant "uiExtension : UIExtensionInsertImage" as UIExt
    participant "Cell" as cell
    participant "InsertImagePanel : JPanel" as cp
    participant "InsertImageController" as ctrl
    participant "imageField: JLabel" as imageField
    participant "applyAction: ApplyAction" as applyAction

    create cp
    UIExt -> cp :  new(uic) 

    cp -> uic : addSelectionListener(this)
    
    create imageField
    cp -> imageField: new()

    create ctrl
    cp -> ctrl : new(uic)

    create applyAction
    cp -> applyAction : new()

    note right of applyAction
        ApplyAction is a innerclass 
        of InsertImagePanel.
        As such, it can access the 
        members of InsertImagePanel,
        for instance, the
        current cell.
    end note

    cp -> imageField : addFocusListener(applyAction)

    == meanwhile a cell is selected...the user insert the image and the label loses the focus ==


    imageField -> applyAction : focusLost(FocusEvent e)
    activate applyAction
    applyAction -> imageField : getInsertImage()
    applyAction -> ctrl : setInsertImage()
    deactivate applyAction

    activate ctrl
    ctrl -> cell : setInsertImage()
    ctrl -> uic : setWorkbookModified(...)
    deactivate ctrl

@enduml