@startuml doc-files/draft_network_search.png
 actor UserSender as User
 participant "<<analysis>>\nNetworkSearchUI" as UI
 participant "<<analysis>>\nNetworkSearchCtrl" as ctrl
 participant "<<analysis>>\nNetwoork" as net
User -> UI : searchInstances()
UI -> ctrl : searchInstances()
ctrl -> net : searchInstances()
User -> UI : enterWoorkBookNameToSearch()
User -> UI : selectInstance()
UI -> ctrl : sendNotification()
ctrl -> net : sendNotification()
@enduml