@startuml doc-files/draft_network_search.png
 actor User as User
 participant "<<analysis>>\nSearchOnAnotherInstancehUI" as UI
 participant "<<analysis>>\nSearchOnAnotherInstancehUICtrl" as ctrl
 participant "<<analysis>>\nNetwork" as net
User -> UI : searchInstances()
UI -> ctrl : searchInstances()
ctrl -> net : searchInstances()
User -> UI : enterWoorkBookNameToSearch()
UI -> ctrl : searchActiveWorkbook(workBookName)
ctrl -> net : searchActiveWorkbook(workBookName)
net --> UI : sendNotification()
@enduml