@startuml doc-files/crm_01_01_updateContact.png
    participant "ContactsPanel : JPanel" as cp
    participant "ContactsController" as ctrl
    participant "contactFrame: JFrame" as jframe
    participant "Contact" as contact
    participant "Persistence" as pers
    participant "RepositoryFactory" as repFactory
    participant "ContactsRepository" as contactsRep



    note right of cp
        double clicks on
        the contact
    end note

    create jframe
    cp -> jframe : new (contact)

    jframe -> ctrl : updateContact(contact)

    ctrl -> pers : getRepositoryFactory()
    pers -> repFactory : newInstance()
    ctrl -> repFactory : getContactsRepository()

    ctrl -> contactsRep : update(contact)

@enduml