@startuml doc-files/import_from_text_file_ipc04_01.png
 actor User
 participant "ImportAction" as iea
 participant "ImportExportUI" as ui
 participant "ImportExportController" as ctrl
 participant "th:Thread" as th
 participant "ImportExportThread" as thr
 participant "ci:CustomImportationExportation" as cie
 participant "SpreadSheetImpl" as ssi
 participant "stream:FileInputStream" as fis
 participant "list:ArrayList<String>" as list

User -> iea : actionPerformed()
iea -> ui : showDialog()
User <-- ui : asks for the column's separator
User -> ui : chooses separator
ui -> ctrl : chooseSeparator(sep)
User <-- ui : asks if the file has a header and if it is \nsupposed to be included in the operation
ui -> ctrl : hasHeader(bool)
ui -> ctrl : includeHeader(bool)
ctrl -> th : th = create(new ImportExportThread())
ctrl -> thr : run()
create cie
thr -> cie : new
thr -> cie : import(sep, header)
create fis
cie -> fis : new
create list
cie -> list : new

loop for each line in the input stream
cie -> fis : st = readLine()
cie -> list : add(st)
end loop

cie -> ssi : map = getCells()

loop for each string in the list, set the content of the cells in map, starting on the top left corner
cie -> list : str = get(i)
cie -> CellImpl : getAddress()
cie -> CellImpl : setContent(str)
end loop

@enduml