@startuml doc-files/macros_09_01_analysis_sequence_add.png

  actor User
  participant "<<analysis>>\nUIExtensionButtons" as UI
  participant "<<analysis>>\nButtonsController" as ctrl
  participant "<<analysis>>\nActionButtonToolBar" as buttons
  participant "<<analysis>>\nJToogleButton" as button
  participant "<<analysis>>\nButtonGroup" as group

	User -> UI: Buttons on Toolbar
	UI -> ctrl: getAllActionButtons()
	User -> UI: select "Add Button"
	UI -> User: Asks Information
	User -> UI: inserts tooltip, icon, action and activate or not
	UI -> User: Asks confirmation
	User -> UI: OK
    UI -> ctrl: buttonInfo(tooltip, icon, Action, activate)
	ctrl -> buttons: new JToogleButton(tooltip, icon, false)
	create button
	buttons -> button: create(tooltip, icon, false)
	buttons -> button: setOnClickListener(Action)
	buttons -> buttons: addButton(button)
   note right of buttons
        The class has a vector of Abstract Buttons
	and it is possible to add and remove a button
    end note
	buttons -> group: add(button)
	UI -> User: success of the use case

@enduml