/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.sendEmail.UI;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Paulo
 */
public class ItemOutBox extends javax.swing.JPanel implements MouseListener {

	private String message;
	private String to;
	private String subject;
	private Border blackBorder = BorderFactory.createLineBorder(Color.BLACK);
	private Border blueBorder = BorderFactory.
		createLineBorder(new Color(0xB8CFE5), 3);
	private OutBoxPanel panel;

	/**
	 * Creates new form ItemOutBox
	 */
	public ItemOutBox(OutBoxPanel panel) {
		initComponents();
		this.panel = panel;
		addMouseListener(this);
		setBorder(blackBorder);
		setFocusable(true);
	}

	public ItemOutBox(OutBoxPanel panel, String To, String subject,
					  String message) {
		initComponents();
		this.to = To;
		this.subject = subject;
		this.message = message;
		setTextOutBoxItem();
		this.panel = panel;
		addMouseListener(this);
		setBorder(blackBorder);
		setFocusable(true);
	}

	public void setDefaultBorder() {
		setBorder(blackBorder);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        subjectLbl = new javax.swing.JLabel();
        messageLbl = new javax.swing.JLabel();

        jLabel1.setText("To:");

        jLabel2.setText("Subject:");

        jLabel3.setText("Message:");

        addressLbl.setText("example@gmail.com");

        subjectLbl.setText("example");

        messageLbl.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subjectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addressLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subjectLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(messageLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JLabel subjectLbl;
    // End of variables declaration//GEN-END:variables

	@Override
	public void mouseClicked(MouseEvent e) {
	}

	@Override
	public void mousePressed(MouseEvent e) {
		setBorder(blueBorder);
		panel.setSelectedItem(this);
	}

	@Override
	public void mouseReleased(MouseEvent e) {
	}

	@Override
	public void mouseEntered(MouseEvent e) {
	}

	@Override
	public void mouseExited(MouseEvent e) {
	}

	private void setTextOutBoxItem() {
		addressLbl.setText(to);
		subjectLbl.setText(subject);
		if (message.length() > 16) {
			messageLbl.setText(message.substring(0, 15));
		} else {
			messageLbl.setText(message);
		}
	}

	public void openMessage() {
		SendEmailDialog dialog = new SendEmailDialog(null, true);
		dialog.openItem(to, subject, message);
		dialog.setVisible(true);
	}
}
