@startuml doc-files/crm_01_01_addEvent.png

    participant "ContactsPanel : JPanel" as cp
    participant "ContactsController" as ctrl
    participant "contactFrame: JFrame" as jframe
    participant "eventFrame: JFrame" as eventFrame
    participant "Contact" as contact
    participant "Agenda" as agenda
    participant "Event" as event
    participant "Persistence" as pers
    participant "RepositoryFactory" as repFactory
    participant "ContactsRepository" as contactsRep


    create jframe
    cp -> jframe : new()

    note right of jframe
        Selects the
        option create Event
    end note

    create eventFrame
    jframe -> eventFrame : new()



    eventFrame -> ctrl : addEvent(timestamp, text)

    ctrl -> contact : addEvent(timestamp,text)
    contact -> agenda : addEvent(timestamp, text)

    create event
    agenda -> event : new(timestamp,text)

    agenda -> agenda : addEvent(event)

    ctrl -> pers : getRepositoryFactory()
    pers -> repFactory : newInstance()
    ctrl -> repFactory : getContactsRepository()

    ctrl -> contactsRep : update(contact)

@enduml