  @startuml doc-files/start_sharing_ipc_01_01.png
  actor User
  participant "<<analysis>>\nStartSharingUI" as UI
  participant "<<analysis>>\nStartSharingCtrl" as ctrl
  participant "<<analysis>>\nSpreadsheet" as sheet
  participant "<<analysis>>\nCell" as cell
  participant "<<analysis>>\nConnection" as connect
  User -> UI : selectCells()
  activate UI
  UI -> ctrl : getCells()
  activate ctrl
  deactivate UI
  ctrl -> sheet : getCell()
  ctrl -> cell : getContent()
  deactivate cell
  deactivate ctrl
  User -> UI : getClients()
  activate UI
  UI -> ctrl : getClients()
  deactivate UI
  activate ctrl
  activate connect
  ctrl -> connect : getClients()
  deactivate ctrl
  activate UI
  User -> UI : selectClient()
  UI -> ctrl : connectChoosenClient()
  activate ctrl
  ctrl -> connect : connectChoosenClient()
  deactivate ctrl
  User -> UI : sendCells()
  UI -> ctrl : sendCellsInfo()
  activate ctrl
  ctrl -> connect : sendCellsInfo()
  deactivate ctrl
  deactivate UI
  @enduml
