@startuml doc-files/ipc_06_01_extension_setup.png
 actor User
 participant "Frame" as fra 
 participant "uic : UIController" as uic
 participant "ExtensionManager" as em
 participant "extension : SecureComunicationExtension" as sse
 participant "mB : MenuBar" as mB
 participant "sB : SideBar" as sB
 participant "panel : SecureComunicationPanel" as panel
 participant "uiExtension : UIExtensionSecureComunication" as uiess
 participant "SecureComunicationMenu" as ssm
 participant "action : SecureComunicationAction" as ssa
 User -> fra : create();
 fra -> uic : create();
 uic -> em : extensions=getExtensions();
 uic -> sse : uiExtension=getUIExtension(this);
 sse -> uiess : create(extension, uic);
 uic -> uic : uiExtensions.add(uiExtension);
 fra -> fra : setJMenuBar(mB);
 fra -> mB : create();
 mB -> uiess : getMenu();
 uiess -> ssm : create(uic);
 fra -> fra : setJSideBar(sB);
 fra -> sB: create();
 sB -> panel:create();
 sB -> uiess:getSideBar();
 ssm -> ssm : add(action);
 ssm -> ssa : create();
@enduml