  @startuml doc-files/ipc_04_02_ssd_export.png
  actor User
  participant "<<analysis>>\nSystem" as s

	User -> s : Exportation (Importation) Link
    s -> User: Show the files
	User -> s: Choose the file to link
	s -> User: Asks about separator
	User -> s: Choose the separator
	s -> User: Confirmation
	User -> s: Confirm
	s -> User: Imports all the information
	User -> s: Changes the cells
	s -> User: Exports to the file
	s -> User: Success of the use case
  @enduml
