@startuml doc-files/draft_macros_02_01.png
 actor User
 participant "CellUI" as UI
 participant "CellCtrl" as ctrl
 participant "Cell" as cell
 participant "Formula" as Formula
 participant "Workbook" as Workbook
 participant "Variable" as Variable


User -> UI : string
activate UI
UI -> ctrl : setContent(string)
activate ctrl
deactivate UI

ctrl -> cell : setContent(string)
activate cell
deactivate ctrl
cell->Formula : create(string)
Formula->Workbook : setContent(value)
activate Workbook
Workbook->Workbook : valida()
alt se nao existir
Workbook->Variable : create(value, workbook)
   Workbook -> Workbook : add(variable)
else
Workbook -> Variable : setVariableValue(value,workbook)
end

@enduml