@startuml doc-files/design_macros_05_02_part1.png
actor User
 participant "CallFunctionUI" as UI
 participant "CallFunctionCtrl" as ctrl
 participant "Language" as language
participant "FunctionCaller" as caller
 participant "FunctionCall" as f_call
participant "Function" as func
User -> UI : show
activate UI
UI -> ctrl : lf = fillList()
deactivate UI
activate ctrl
ctrl -> language : lf = getFunctions()
deactivate ctrl
activate UI
UI ->ctrl : lf = fillListOperators(lf)
activate ctrl
ctrl -> language : lf = getOpertions()
deactivate ctrl
UI -> UI : fillFunctionsList(lf)
User -> UI : choose function
UI -> ctrl : func_def = chooseFunction(f)
deactivate UI
activate ctrl
ctrl -> language : func = getFunction(f)
deactivate ctrl
activate UI
User -> UI : Fill Data and Enter
UI -> ctrl : validateParameters(lp, func_def)
UI -> ctrl : value = showResult(func_def)
activate ctrl
ctrl -> caller : value = executeFunc(func_def)
deactivate ctrl
caller -> f_call : create(function, arguments) 
activate f_call
caller -> f_call : value = evaluate()
deactivate caller
f_call -> func : value = applyTo(arguments)
activate func
deactivate f_call
UI -> UI : setText(value)
UI -> ctrl : addFunctionFormulasPanel(func_def)
participant "FormulaPanel" as panel
ctrl -> panel : addFormula(formula)

@enduml