@startuml doc-files/select_game_and_partner_ipc_07_01.png
 actor User
 participant "SelectGameAction" as sga
 participant "PlayerInfo" as playerInfo
 participant "ChoosePartner" as cp
 participant "SelectGameController" as sgc
 participant "Player" as player
 participant "GameScene" as scene
 participant "ActiveGamesPanel" as agp
 participant "<<Service>>\nNetworkService" as netw
 participant "<<Service>>\nNetworkSendService" as netws
 participant "SearchPartnersServer" as server

 User -> sga : actionPerformed()
 sga -> playerInfo : showDialog()
 User -> playerInfo : chooseGame();
 playerInfo -> scene : showDialog();
 User -> playerInfo : chooseName();
 playerInfo -> sgc : setPlayerName(name);
 sgc -> player : setName(name);
 User -> playerInfo : chooseImage();
 playerInfo -> sgc : setPlayerImage(image);
 sgc -> player : setPlayerImage(image);

 playerInfo -> cp : showDialog(lc);

 cp -> sgc : lc=searchInstances();
 sgc->netw : lc=serachIntances();
 netw -> netws : lc=searchActiveIntances();

 cp -> sgc : startGameServer(gamescene, player, this);
 sgc->netw : startGameServer(dialog, player, partnersDialog);
 create server
 netw -> server : create(dialog, player, partnersDialog);
 server->server : run();

 User <-- cp : show active clients

 alt client that wants to connect
 User -> cp : chooseClient();
 cp -> sgc : establishConnection(address);
 sgc -> netw : establishConnectionToUser(address);
 netw -> netws : establishConnectionToUser(address);

 cp->sgc : sendUserInfo(player);
 netw->netws : sendUserInfo(player);
 cp -> scene : setPlayerData(player);
 cp ->sgc : activeGame(game);
 sgc -> agp : activeGame(game);
 cp -> scene : setVisible(true);

 end alt

 alt client that receives the connection
 server->server : waitToReceiveOtherPlayerInfo();
 server->netw : establishConnetction(address);
 server->server : run();
 server->server : waitForMessage();
 cp->sgc : sendUserInfo(player);
 netw->netws : sendUserInfo(player);
 server -> scene : setPlayerData(player);
 server ->sgc : activeGame(game);
 sgc -> agp : activeGame(game);
 server -> scene : setVisible(true);

 end alt

@enduml