@startuml doc-files/crm_01_01_analise_classes.png

    class "<<analysis>> Persistence" as Persistence{
        +getRepositoryFactory()
    }

    interface "<<analysis>> RepositoryFactory" as RepositoryFactory{
        +newInstance()
    }

    class "<<analysis>> ContactsRepository" as ContactsRepository{
        +update(contact)
    }

    class "<<analysis>> Address" as Address{
        -String street
		-String city
		-String postal_code
		-String locality
        -String country
    }

    class "<<analysis>> Contact" as Contact{
		-Address main_address
		-Address secundary_address
    }

    class "<<analysis>> ContactController" as ContactController{
        +updateContact(Contact c)
		+getAllContacts()
    }

	Address <|-- Contact
    RepositoryFactory <|-- Persistence
    ContactsRepository <|-- RepositoryFactory
    ContactsRepository <|-- ContactController
	Contact <|-- ContactController

@enduml
