@startuml doc-files/Extension_setup_ipc_01_02.png
 actor User
 participant "Frame" as fra 
 participant "uic : UIController" as uic
 participant "ExtensionManager" as em
 participant "extension : StartSharingExtension" as sse
 participant "mB : MenuBar" as mB
 participant "uiExtension : UIExtensionStartSharing" as uiess
 participant "StartSharingMenu" as ssm
 participant "action : StartSharingAction" as ssa
participant "action : StartAutomaticSharingAction" as sasa
 User -> fra : create();
 fra -> uic : create();
 uic -> em : extensions=getExtensions();
 uic -> sse : uiExtension=getUIExtension(this);
 sse -> uiess : create(extension, uic);
 uic -> uic : uiExtensions.add(uiExtension);
 fra -> fra : setJMenuBar(mB);
 fra -> mB : create();
 mB -> uiess : getMenu();
 uiess -> ssm : create(uic);
 ssm -> ssm : add(action);
 ssm -> ssa : create();
ssm -> sasa : create();
@enduml