/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.importXML.ui;

import csheets.CleanSheets;
import csheets.core.Spreadsheet;
import csheets.ext.importXML.ImportController;
import csheets.ui.ctrl.UIController;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio
 */
public class ImportAsDialog extends javax.swing.JDialog {

	private UIController uiController;
	private CleanSheets app;
	private ImportController importController;
	private File file;
	private Spreadsheet sheet;

	/**
	 * Creates new form ImportAsDialog
	 *
	 * @param parent
	 * @param modal
	 * @param uiController
	 * @param app
	 */
	public ImportAsDialog(java.awt.Frame parent, boolean modal,
						  UIController uiController, CleanSheets app) {
		super(parent, "Import As", modal);
		this.uiController = uiController;
		this.app = app;
		this.importController = new ImportController(uiController);
		initComponents();

		int sheets = uiController.getActiveWorkbook().getSpreadsheetCount();

		for (int i = 0; i < sheets; i++) {
			sheetComboBox.addItem(uiController.getActiveWorkbook().
				getSpreadsheet(i).getTitle());
		}
		sheetComboBox.addItem("New SpreadSheet");
		fileChooserButton.setEnabled(false);
		jLabel1.setEnabled(false);
		fileLabbel.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importAsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fileChooserButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        sheetComboBox = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        fileLabbel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        importAsButton.setText("Import");
        importAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importAsButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose the file to import :");

        fileChooserButton.setText("File");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Choose spreadsheet to set:");

        sheetComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        sheetComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sheetComboBoxActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        fileLabbel.setText("...");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(importAsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileChooserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileLabbel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sheetComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sheetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileChooserButton)
                    .addComponent(fileLabbel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importAsButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void importAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importAsButtonActionPerformed
		if (sheetComboBox.getSelectedItem().equals("New SpreadSheet")) {
			sheet = null;
		} else {
			sheet = uiController.getActiveWorkbook().
				getSpreadsheet(sheetComboBox.getSelectedIndex());
		}

		if (file == null) {
			JOptionPane.
				showMessageDialog(null, "Choose a file to import first!", "Alert", JOptionPane.ERROR_MESSAGE);
		} else {
			String fileExtension = file.getAbsolutePath().substring(file.
				getAbsolutePath().lastIndexOf('.'));
			importController.
				importXML(file.getAbsolutePath(), fileExtension, sheet, uiController.
						  getActiveWorkbook());
			dispose();
			JOptionPane.
				showMessageDialog(null, "File imported with success!", "Success", JOptionPane.INFORMATION_MESSAGE);
		}
    }//GEN-LAST:event_importAsButtonActionPerformed

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
		JFileChooser chooser = new JFileChooser();
		chooser.showOpenDialog(null);
		file = chooser.getSelectedFile();
		if (file != null) {
			fileLabbel.setText(file.getName());
		}
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void sheetComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sheetComboBoxActionPerformed
		fileChooserButton.setEnabled(true);
		jLabel1.setEnabled(true);
		fileLabbel.setEnabled(true);
    }//GEN-LAST:event_sheetComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel fileLabbel;
    private javax.swing.JButton importAsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox sheetComboBox;
    // End of variables declaration//GEN-END:variables
}
