@startuml doc-files/ipc08_01_design2.png
    participant "uic: UIController" as uic
    participant "uiExtension : UIExtensionFileSharing" as UIExt
    participant "FileSharingPanel : JPanel" as cp
    participant "FileSharingController" as ctrl
    participant "FileSharingUI : JFrame" as fsui
    participant "TCP : TCP" as tcp
    participant "Socket : Socket" as skt

    UIExt -> cp :  new(uic) 
    cp -> ctrl : new(uic) 
    uic -> cp : ActionPerformed()
    cp -> ctrl : ActionPerformed()
    alt true
        ctrl -> ctrl : startService()
        ctrl -> fsui : create()
        ctrl-> tcp : ServerFilesList()
        ctrl  ->tcp  : getClientFilesList()
        tcp --> ctrl :
        ctrl -> fsui : display()
    end
    alt false
        ctrl -> ctrl : stopService()
    end
@enduml
