  @startuml doc-files/ipc08_01_analysis.png
  actor User
  participant "<<analysis>>\nFileSharingUI" as UI
  participant "<<analysis>>\nFileSharingCtrl" as ctrl
  participant "<<analysis>>\nConnection" as connect
  User -> UI : startService()
  activate UI
  UI -> ctrl : getClients()
  deactivate UI
  activate ctrl
  activate connect
  ctrl -> connect : getClients()
  connect --> ctrl 
  ctrl --> UI
  UI -> UI : showClients()
  deactivate ctrl
  User -> UI : selectClient()
  activate UI
  UI -> ctrl : connectChoosenClient()
  deactivate UI
  activate ctrl
  ctrl -> connect : connectChoosenClient()
  deactivate ctrl
  connect --> ctrl
  ctrl --> UI
  UI -> UI : MSG()
  @enduml