@startuml doc-files/draft_send_email.png
participant User as usr
participant "SendEmailUI" as seui
participant "SendEmailAction" as sea
participant "EmailController" as emc
participant "e: Email" as em
participant "<<Service>>\nEmailSender" as emse
usr -> seui : enterData(receiver, subject, message)
usr -> seui : send()
seui -> sea : String content = getSelectCellsContent()
seui -> emc : e = createEmail(receiver, subject, mensagem , content)
emc -> em : e = create(receiver, subject, mensagem)
seui -> emc : sendEmail(e)
emc -> emse : sendEmail(e)
@enduml