@startuml doc-files/sequence_diagram_receiver.png
actor Receiver as user
participant "dialog : SearchOnAnotherInstanceDialog" as said
participant "UIController" as uic
participant "SearchOnAnotherInstanceController" as saic
participant "SearchOnAnotherInstanceServer" as serv
participant "notEve : NotificationEvent" as notEve
participant "<<Service>>\nNetworkService" as net
participant "SearchOnAnotherInstanceClient" as soaic
== When receive the search request ==
serv -> serv : socket.accept()
serv -> notEve : create(address, workbookName)
serv -> serv : setChanged()
serv -> serv : notifyObservers(repEve)
serv -> said : update()
said -> uic : getOpenWorkbookByFileName(workbookName)
said -> saic : sendWorkbook(address, openWorkbook)
saic -> net : sendWorkbook(address, openWorkbook)
net -> soaic : create()
net -> soaic : .sendWorkbook(address, workbook)
@enduml