@startuml doc-files/sequence_diagram.png
actor Sender as user
participant "dialog : SearchOnAnotherInstanceDialog" as said
participant "SearchOnAnotherInstanceController" as saic
participant "<<Service>>\nNetworkService" as net
participant "SearchOnAnotherInstanceClient" as soaic
participant "repwat : ReportWatch" as repWat
participant "<<Service>>\nReportCreater" as repCrea
participant "SearchOnAnotherInstanceServer" as serv
participant "repoEve : ReportEvent" as repoEve
user -> said : searchActionPerformed()
said -> saic : sendSearchRequest(address, workbookName)
saic -> net : sendSearchRequest(address, workbookName)
net -> soaic : create()
net -> soaic : sendWorkbookName(address, workbookName)
== Wait response to request ==
serv -> serv : socket.accept()
serv -> repoEve : create(workbook)
serv -> serv : setChanged()
serv -> serv : notifyObservers(repoEve)
serv -> repWat : update()
repWat -> repoEve : workbook = getWorkbook()
repWat -> repCrea : createResume(workbook)
repWat -> repWat : setChanged()
repWat -> repWat : notifyObservers(strResume)
repWat -> said : update()
said -> said : showResume()
@enduml